config/routes.rb
Rails.application.routes.draw do
        
  devise_for :users
  scope "/admin" do
    resources :users  

  
    patch '/users/:id/edit', to: 'users#edit', :as => 'admin/users/edit'

  end

    match '/contacts',     to: 'contacts#new',             via: 'get'
    resources "contacts", only: [:new, :create]
    
    resources :topics do
      resources :posts, except: [:index] 
    end
      resources :posts do
        resources :comments, except: [:index]
          resources :favorites, only: [:create, :destroy]


        post '/up-vote' => 'votes#up_vote', as: :up_vote
        post '/down-vote' => 'votes#down_vote', as: :down_vote

      end
  


  get 'home/about'

  get 'home/membership'

  get 'home/index'

    root to: 'home#index'


end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_many :posts, dependent: :destroy
	belongs_to :user
	

	


	scope :visible_to_bronze, -> {where(:bronze => true)}
	scope :visible_to_silver, -> {where(:silver => true)}
	scope :visible_to_gold, -> {where(:gold => true)}
	scope :visible_to_platinum, -> {where(:platinum => true)}
	scope :visible_to_admin, -> {where(:admin => true)}

	


end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

 
  def index
   @topics = Topic.all 
   
  	authorize @topics 
  end

  def new
  	@topic = Topic.new
  	authorize @topic 
  end

  def show
  	@topic = Topic.find(params[:id])
  	@posts = @topic.posts.all.paginate(page: params[:page], per_page: 10)
    
  	authorize @topic
  end

  def edit
  	@topic = Topic.find(params[:id])
  	authorize @topic 
  end

  def create
  	@topic = current_user.topics.build(topic_params)
  	authorize @topic
  	if @topic.save 
  		redirect_to @topic, notice: "Topic was saved successfully."
  	else
  		flash[:error] = "Error creating topic. Please try again."
  		render :new
  	end
  end

  	def update
  		@topic = Topic.find(params[:id])
  		authorize @topic
  		if @topic.update_attributes(topic_params)
  			redirect_to @topic
  		else
  			flash[:error] = "Error saving topic. Please try again."
  			render :edit
  		end
  	end
  
  def destroy
    @topic = Topic.find(params[:id])
    name = @topic.name 

    authorize @topic
    if @topic.destroy
      flash[:notice] = "\"#{name}\"was deleted successfully."
      redirect_to topics_path
    else
      flash[:error] = "There was an error deleting this topic."
      render :show
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:name, :description, :public, :bronze, :silver, :gold, :platinum)
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<<div class="row">
	<div class="col-md-4">
		<p>Guidelines for topics: </p>
		<ul>
			<li>Topics should make sense. </li>
			<li> Topics should be pithy. </li>
		</ul>
	</div>
	<div class="col-md-8">
		<%= form_for @topic do |f| %>
			<div class="form-group">
				<%= f.label :name %>
				<%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
			</div>
			<div class="form-group">
				<%= f.label :description %>
				<%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>	
			</div>
			<div class="form-group">
				<%= f.label :public, class: 'checkbox' do %>
					<%= f.check_box :public %> Public topic
				<% end %>
			</div>
			<%= f.submit "Save", class: 'btn btn-success' %>
			<% end %>
	</div>
</div>

app/views/topics/index.html.erb
<center><h1> Member Content </h1></center>
<br/>
<div class="row">
<div class="col-md-8">
	<br/>
	<% if current_user.bronze? %>
	<% @topics.visible_to_bronze.paginate(page: params[:page], per_page: 10).all.each  do |topic| %>
		<div class="media">
			<div class="media-body">
				<h4 class="media-heading">
				<%= link_to (markdown_to_html topic.name), topic %>
				</h4>
				<small>
					<%= markdown_to_html topic.description %>
				</small>
			</div>
		</div>
		<% end %>
	<% end %>

<% if current_user.silver? %>
<% @topics.visible_to_silver.paginate(page: params[:page], per_page: 10).all.each  do |topic| %>
		<div class="media">
			<div class="media-body">
				<h4 class="media-heading">
				<%= link_to (markdown_to_html topic.name), topic %>
				</h4>
				<small>
					<%= markdown_to_html topic.description %>
				</small>
			</div>
		</div>
		<% end %>
	<% end %>

<% if current_user.gold? %>
<% @topics.visible_to_gold.paginate(page: params[:page], per_page: 10).all.each  do |topic| %>
		<div class="media">
			<div class="media-body">
				<h4 class="media-heading">
				<%= link_to (markdown_to_html topic.name), topic %>
				</h4>
				<small>
					<%= markdown_to_html topic.description %>
				</small>
			</div>
		</div>
		<% end %>
	<% end %>

<% if current_user.platinum? %>
<% @topics.visible_to_platinum.paginate(page: params[:page], per_page: 10).all.each  do |topic| %>
		<div class="media">
			<div class="media-body">
				<h4 class="media-heading">
				<%= link_to (markdown_to_html topic.name), topic %>
				</h4>
				<small>
					<%= markdown_to_html topic.description %>
				</small>
			</div>
		</div>
		<% end %>
	<% end %>
</div>


<div class="col-md-4">
	<% if policy(Topic.new).create? %>
		<%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
	<% end %>
</div>
</div>

app/views/topics/new.html.erb
<h1> New Topic </h1>

<div class="row">
	<div class="col-md-4">
		<p>Guidelines for topics: </p>
		<ul>
			<li>Topics should make sense. </li>
			<li> Topics should be pithy. </li>
		</ul>
	</div>
	<div class="col-md-8">
		<%= form_for @topic do |f| %>
			<div class="form-group">
				<%= f.label :name %>
				<%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
			</div>
			<div class="form-group">
				<%= f.label :description %>
				<%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>	
			</div>
			<div class="form-group">
				<%= f.label :public, class: 'checkbox' do %>
					<%= f.check_box :public %> Public Content	
			</div>
			<% end %>
			<div class="form-group">
				<%= f.label :bronze, class: 'checkbox' do %>
					<%= f.check_box :bronze %> Bronze Content
			<% end %>
			</div>
			<div class="form-group">
				<%= f.label :bronze, class: 'checkbox' do %>
					<%= f.check_box :silver %> Silver Content
			<% end %>
			</div>
			<div class="form-group">
				<%= f.label :bronze, class: 'checkbox' do %>
					<%= f.check_box :gold %> Gold Content
			<% end %>
			</div>
			<div class="form-group">
				<%= f.label :bronze, class: 'checkbox' do %>
					<%= f.check_box :platinum %> Platinum Content
			<%= f.submit "Save", class: 'btn btn-success' %>
				</div>
			<% end %>
		<% end %>
		

	</div>
</div>

app/views/topics/show.html.erb
<h1><%=markdown_to_html @topic.name %></h1>

<% if policy(@topic).update? %>
	<%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
<% end %>

<div class="row">
	<div class="col-md-8">
	<br/>
		<p><%= link_to "Back", topics_path, class: 'btn btn-primary btn-sm' %></p>

		<p class="lead"> <%=markdown_to_html @topic.description %></p>
		<% @posts.each do |post| %>
			<div class="media">
				<%= render partial: 'votes/voter', locals: {post: post} %>
				<div class="media-body">
					<h4 class="media-heading">
						<%= link_to (markdown_to_html post.title), [@topic, post] %>
					</h4>
					
						<small>
							<%= image_tag(post.user.avatar.tiny.url) if post.user.avatar? %>
							submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %> <br/>
							<%=  post.comments.count %>  Comments 
						</small>

				</div>
			</div>
		<% end %>
	</div>
	<div class="col-md-4">
		<% if policy(Post.new).create? %>
			<%= link_to "New Post", new_topic_post_path(@topic, @post), class: 'btn btn-success' %>
		<% end %>

		<% if policy(@topic).destroy? %>
			<%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you wish to delete this topic?' } %>
		<% end %>
	</div>
</div>