config/routes.rb
Rails.application.routes.draw do
        
  devise_for :users
  scope "/admin" do
    resources :users  

  
    patch '/users/:id/edit', to: 'users#edit', :as => 'admin/users/edit'

  end

    match '/contacts',     to: 'contacts#new',             via: 'get'
    resources "contacts", only: [:new, :create]
    
    resources :topics do
      resources :posts, except: [:index] 
    end
      resources :posts do
        resources :comments, except: [:index]
          resources :favorites, only: [:create, :destroy]


        post '/up-vote' => 'votes#up_vote', as: :up_vote
        post '/down-vote' => 'votes#down_vote', as: :down_vote

      end
  


  get 'home/about'

  get 'home/membership'

  get 'home/index'

    root to: 'home#index'


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :posts
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy 
  has_many :favorites, dependent: :destroy
  has_many :topics
  
    mount_uploader :avatar, AvatarUploader

  def favorited(post)
    favorites.where(post_id: post.id).first
  end

  def admin?
  	self.role == 'admin'
  end

  def platinum?
  	self.role === 'platinum' || self.role === 'admin'
  end

  def bronze?
  	self.role === 'bronze' || self.role === 'silver' || self.role === 'gold' || self.role === 'platinum' || self.role=== 'admin'
  end

  def silver?
  	self.role === 'silver' || self.role === 'gold' || self.role === 'platinum' || self.role ==='admin'
  end

  def gold?
  	self.role === 'gold' || self.role === 'platinum' || self.role === 'admin'
  end

  def price
    return 500
  end
  
   default_scope { order('users.name ASC') }
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!



	def edit 
		@user = User.find(params[:id])

		if @user.update_attributes(user_params)
  			flash[:notice] = "User was updated."
  			redirect_to @user
  		else
  			flash[:error] = "There was an error saving the post. Please try again."
  			render :edit
  		end
	end

	def show
		@user = User.find(params[:id])
		@posts = @user.posts
		@comments = @user.comments
	end

	def index
		@users = User.all
	end

	private

	def user_params
		params.require(:user).permit(:name, :avatar, :avatar_cache, :email_favorites, :role)
	end
end

app/views/users/index.html.erb
<div class="row">
	<div class="col-md-2">
	</div>
	<div class="col-md-8">
		<center><h1> Users </h1></center>
		<br/>
		<h3> Only administrators can view and edit user information. </h3>
		<br/>
		<% if current_user.admin? %>	
		<% @users.each do |user|%>
		<p><%= link_to user.name, user  %></p>
		<% end %>
		<% end %>
	</div>
	<div class="col-md-2">
	</div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-md-2">
	</div>
	<div class="col-md-8">
		<br/>
		<center><h1> <%= @user.name %></h1></center>
		<br/>
		<h2> Membership Level</h2>
		<p>Edit user membership below. This will determine what content is available to them.</p>
		<p> Keep in mind that content is tiered; Silver can see all of Silver and Bronze, Gold can see all of Gold, Silver, and Bronze, etc. </p>
		<br/>
 		<%if current_user.role == 'admin' %>
   		<h3> Edit User Membership Level</h3>
   
   		<%= form_for(@user, url: admin_users_edit_path, html: { method: :patch }) do |f| %>  

    <div class="form-group">
    <%= f.label :role %> <%= f.text_field :role, class: 'form-control', placeholder: "Edit Membership Level", autofocus: true %>
     </div>
 
  <div class="form-group"> <%= f.submit "Update", class: 'btn btn-success' %>
    </div>
    
	</div>
	<div class="col-md-2">
	</div>
</div>
		<% end %>
		<% end %> 