config/routes.rb
Rails.application.routes.draw do
        
  devise_for :users
  scope "/admin" do
    resources :users  

  
    patch '/users/:id/edit', to: 'users#edit', :as => 'admin/users/edit'

  end

    match '/contacts',     to: 'contacts#new',             via: 'get'
    resources "contacts", only: [:new, :create]
    
    resources :topics do
      resources :posts, except: [:index] 
    end
      resources :posts do
        resources :comments, except: [:index]
          resources :favorites, only: [:create, :destroy]


        post '/up-vote' => 'votes#up_vote', as: :up_vote
        post '/down-vote' => 'votes#down_vote', as: :down_vote

      end
  


  get 'home/about'

  get 'home/membership'

  get 'home/index'

    root to: 'home#index'


end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	has_many :votes
	has_many :favorites, dependent: :destroy

	
	belongs_to :user
		belongs_to :topic

	def up_votes
		votes.where(value: 1).count
	end

	def down_votes
		votes.where(value: -1).count
	end

	def points
		votes.sum(:value)
	end

	def update_rank
		age_in_days = (created_at - Time.new(1970,1,1)) / (60*60*24)
		new_rank = points + age_in_days

		update_attribute(:rank, new_rank)
	end

	default_scope { order('rank DESC')}

	validates :title, length: {minimum: 5}, presence: true
	validates :body, length: {minimum: 10}, presence: true
	validates :topic, presence: true
	validates :user, presence: true
	

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @topic = Topic.find(params[:topic_id])
  	@post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.all
  end
    

  def new
    @topic = Topic.find(params[:topic_id])
  	@post = Post.new 
      authorize @post
  end

  def create
    @topic = Topic.find(params[:topic_id])
  	@post = current_user.posts.build(post_params)
    @post.topic = @topic
      authorize @post
  	if @post.save
  		flash[:notice] = "Post was saved."
  		redirect_to [@topic, @post]
  	else
  		flash[:error] = "There was an error saving the post. Please try again."
  		render :new
  	end
  end

  def edit
  	@post = Post.find(params[:id])
    authorize @post
  end

  def update
    @topic = Topic.find(params[:topic_id])
  	@post = Post.find(params[:id])
    authorize @post 
  	
  	if @post.update_attributes(post_params)
  		flash[:notice] = "Post was updated."
  		redirect_to [@topic, @post] 
  	else
  		flash[:error] = "There was an error saving the post. Please try again."
  		render :edit
  	end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    title = @post.title
    authorize @post
     

    authorize @post
    if @post.destroy
      flash[:notice] = "\"#{title}\"was deleted successfully."
      redirect_to topics_path
    else
      flash[:error] = "There was an error deleting this topic."
      render :show
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<br>
<h1>Edit Post</h1>

<div class="row" id="spacer">
	<div class="col-md-4">
		<h3> Posting Guidlines </h3>
		<ul>
			<li> Carefully check grammar and spelling.</li>
			<li> Ensure all information is accurate.</li>
			<li> Reference our store page when possible. </li>
			<li> Be interesting.</li>
			<li> Post something useful for our members. </li>
			<li> Use Markdown to style your Posts. <a href="https://daringfireball.net/projects/markdown/basics">Reference guide</a></li>
		</ul>
	</div>
	<div class="col-md-8">	
		<%= form_for [@topic, @post] do |f| %>
			<div class="form-group">
				<%= f.label :title %>
				<%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
			</div>
			<div class="form-group">		
				<%= f.label :body %>
				<%= f.text_area :body, class: 'form-control', placeholder: "Enter post text" %>
			</div>
			<div class="form-group">			
				<%= f.submit "Save", class: 'btn btn-success' %>
			</div>
		<% end %>
	</div>
</div>	

app/views/posts/new.html.erb
<br>
<h1> New Post </h1>

<div class="row" id="spacer">
	<div class="col-md-4">
		<h3> Posting Guidlines </h3>
		<ul>
			<li> Carefully check grammar and spelling.</li>
			<li> Ensure all information is accurate.</li>
			<li> Reference our store page when possible. </li>
			<li> Be interesting.</li>
			<li> Post something useful for our members. </li>
			<li> Use Markdown to style your Posts. <a href="https://daringfireball.net/projects/markdown/basics">Reference guide</a></li>
		</ul>
	</div>
	<div class="col-md-8">	
		<%= form_for [@topic, @post] do |f| %>
			<div class="form-group">
				<%= f.label :title %>
				<%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
			</div>
			<div class="form-group">		
				<%= f.label :body %>
				<%= f.text_area :body, class: 'form-control', placeholder: "Enter post text" %>
			</div>
			<div class="form-group">			
				<%= f.submit "Save", class: 'btn btn-success' %>
			</div>
		<% end %>
	</div>
	
</div>	

app/views/posts/show.html.erb
<h1><%= markdown_to_html @post.title %></h1>
	
<div class="row">
	<div class="col-md-8">
		<br/>
		<p><%= link_to "Back to Content Home", topics_path, class: 'btn btn-primary btn-sm' %></p>

		<%= render partial: 'votes/voter', locals: { post: @post } %>

		<small>
			<%= image_tag(@post.user.avatar.tiny.url) if @post.user.avatar? %>
			submitted <%= time_ago_in_words(@post.created_at) %> ago by
			<%= @post.user.name %>
		</small>
		
		<p><% if policy(@post).edit? %>
		<%= link_to "Edit", edit_topic_post_path(@topic, @post), class: 'btn btn-success' %>
		<% end %>

		 <% if policy(@post).destroy? %>
		<%= link_to "Delete Post", [@topic, @post], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you wish to delete this post?' } %>
		<% end %> </p>

		<div>
     		<h3><%= pluralize(@post.points, 'point') %></h3>
     			<small>
      			<%= pluralize(@post.up_votes, 'up vote') %>,
       			<%= pluralize(@post.down_votes, 'down vote') %>
     			</small>
   		</div>
   			<%= render partial: 'favorites/favorite', locals: { post: @post } %>
		<p><%= markdown_to_html @post.body %></p>

		<!-- Comment form !-->
		<h3> New Comment </h3>
	
		<h4> Posting Guidlines </h4>
		<ul>
			<li> Carefully check grammar and spelling.</li>
			<li> Be interesting.</li>
			<li> Post something useful for our members. </li>
			<li> Use Markdown to style your Posts. <a href="https://daringfireball.net/projects/markdown/basics">Reference guide</a></li>
		</ul>
		
		<div class="col-md-8">	
		<%= form_for [@post, Comment.new] do |f| %>
			
			<div class="form-group">		
				<%= f.label :body %>
				<%= f.text_area :body, class: 'form-control', placeholder: "Enter comment text" %>
			</div>
			<div class="form-group">			
				<%= f.submit "Save", class: 'btn btn-success' %>
			</div>
		<% end %>
		</div>
		
	</div>
		
	
	<div class="col-md-8" id="comments">
	<h4> Comments</h4>
		<%= render :partial => @post.comments %>
	</div>
</div>	