config/routes.rb
Rails.application.routes.draw do
        
  devise_for :users
  scope "/admin" do
    resources :users  

  
    patch '/users/:id/edit', to: 'users#edit', :as => 'admin/users/edit'

  end

    match '/contacts',     to: 'contacts#new',             via: 'get'
    resources "contacts", only: [:new, :create]
    
    resources :topics do
      resources :posts, except: [:index] 
    end
      resources :posts do
        resources :comments, except: [:index]
          resources :favorites, only: [:create, :destroy]


        post '/up-vote' => 'votes#up_vote', as: :up_vote
        post '/down-vote' => 'votes#down_vote', as: :down_vote

      end
  


  get 'home/about'

  get 'home/membership'

  get 'home/index'

    root to: 'home#index'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inayan Escrima</title>
  	<meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<ul class="nav nav-tabs">
			<li> <%= link_to "Home", home_index_path %></li>
			<li> <%= link_to "About", home_about_path %></li>
			<li> <%= link_to "Membership", home_membership_path %></li>
			<li> <%= link_to "Contact", contacts_path %></li>
			<% if current_user %>
			<li> <%= link_to "Member Content Area", topics_path %></li>
			<% end %>	
			<% if current_user && current_user.admin? %>
			<li> <%= link_to "User Administration", users_path %></li>
			<% end %>
			<div class="pull-right user-info">
				<% if current_user %>
					<%= image_tag(current_user.avatar.tiny.url) if current_user.avatar? %>
				Hello <%= link_to (current_user.name || current_user.email), edit_user_registration_path %>! <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
				<% else %>
				<%= link_to "Sign in", new_user_session_path %> 
				<% end %>
				</div>
			</ul>	

		

			<% if flash[:notice] %>
		<div class="alert alert-success">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<%= flash[:notice] %>
		</div>
	<% elsif flash[:error] %>
		<div class="alert alert-danger">
			<button type="button" class="close" data-dismiss="alert">&times;</button>		
			<%= flash[:error] %>
		</div>
	<% elsif flash[:alert] %>
		<div class="alert alert-warning">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<%= flash[:alert] %>
		</div>
	<% end %>
	


		<%= yield %>
	</div>
</body>
</html>